### ISSUE TITLE
ChartBuilder 2.0 crashes Chrome as soon as selecting date frequency of two months

### ISSUE THREAD

**Issue by janhoogeveen** [Quartz/Chartbuilder#162] opened 2015-06-23 12:46 UTC
To reproduce:

Go to http://quartz.github.io/Chartbuilder/build/
Click on Date Frequency
Set to Three months

Chrome 43 64-bit on Yosemite.

**Comment by nsonnad** [comment] 2015-06-23 13:11
Believe this is a duplicate of #147. Do you have a time span that for two months would generate a fairly large number of dates?

**Comment by mushishi78** [comment] 2015-06-23 19:30
Yeah it's cause it generating a lot of dates. With the default data, it completely crashes if you select 1 hour and it just about survives if you select 1 day

**Comment by nsonnad** [comment] 2015-06-23 21:56
Yep. I'm going to close #147 in favor of this. We plan on disabling options that would create more than some threshold of dates. If anyone would like to take it on before then, I have some ideas on implementation.

**Closed** 2020-05-28 16:55 UTC
Labels: enhancement
